name: Test

on:
  push:
    branches: [ "hamba-avro"]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.14

      - name: Test
        run: |
          sudo apt-get install -y librdkafka-dev gcc
          go test
