name: Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.14

      - name: Test
        run: go test